name: CI

permissions:
  actions: read
  contents: read
  packages: read
  pull-requests: read # for nx shas

on:
  merge_group: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  ci-validate:
    uses: Inthememory/project-config/.github/workflows/ci.yml@8a73c29a9443fbee8ba6f5d7d69201d0f334d16d # main
    secrets: inherit
