name: CI

permissions:
  actions: read
  contents: read
  packages: read
  pull-requests: read # for nx shas

on:
  merge_group: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  ci-validate:
    uses: Inthememory/project-config/.github/workflows/ci.yml@0a15b12c959e7881b710f40f70ce2d4ecde98df4 # main
    secrets: inherit
