name: 'Pull Request'
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  actions: read    # run checkout and reusable actions
  contents: read   # checkout
  packages: read   # install deps from GitHub Packages (ci-setup, ci-install)
jobs:
  pr-validate:
    uses: Inthememory/project-config/.github/workflows/pr.yml@a4c5ab5dbc89ef44ac03d8c741ca1900959cdad8 # main
    secrets: inherit
