name: 'Pull Request'
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  actions: read    # run checkout and reusable actions
  contents: read   # checkout
  packages: read   # install deps from GitHub Packages (ci-setup, ci-install)
jobs:
  pr-validate:
    uses: Inthememory/project-config/.github/workflows/pr.yml@b34f74fb2592f4e640a45a4b2abb9c0a1503150f # main
    secrets: inherit
